create table if not exists public.collection_runs (
  id uuid primary key default gen_random_uuid(),
  collection_key text not null unique,
  colony_id uuid not null references public.colonies(id) on delete cascade,
  experiment_id uuid references public.experiments(id) on delete set null,
  collector text not null,
  runtime_sha text,
  status text not null default 'running' check (status in ('running','succeeded','failed')),
  source_request_id text,
  expected_samples integer check (expected_samples is null or expected_samples > 0),
  interval_ms integer check (interval_ms is null or interval_ms >= 0),
  sample_count integer not null default 0 check (sample_count >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telemetry_samples (
  id bigint generated by default as identity primary key,
  sample_key text not null unique,
  collection_run_id uuid not null references public.collection_runs(id) on delete cascade,
  colony_id uuid not null references public.colonies(id) on delete cascade,
  experiment_id uuid references public.experiments(id) on delete set null,
  sequence integer not null check (sequence >= 0),
  captured_at timestamptz not null,
  game_tick bigint,
  runtime_sha text,
  schema text not null,
  schema_version integer not null check (schema_version > 0),
  payload jsonb not null,
  inserted_at timestamptz not null default now(),
  unique (collection_run_id, sequence)
);

create index if not exists collection_runs_colony_started_idx
  on public.collection_runs (colony_id, started_at desc);
create index if not exists collection_runs_experiment_idx
  on public.collection_runs (experiment_id);
create index if not exists telemetry_samples_run_sequence_idx
  on public.telemetry_samples (collection_run_id, sequence);
create index if not exists telemetry_samples_colony_captured_idx
  on public.telemetry_samples (colony_id, captured_at desc);
create index if not exists telemetry_samples_experiment_idx
  on public.telemetry_samples (experiment_id, sequence);
create index if not exists telemetry_samples_game_tick_idx
  on public.telemetry_samples (game_tick desc) where game_tick is not null;

comment on table public.collection_runs is 'Durable executions of external Screeps telemetry collectors. Supabase is the system of record; runners are replaceable executors.';
comment on table public.telemetry_samples is 'Idempotent longitudinal Screeps observations persisted as they are collected. Payloads are schema-versioned JSONB; identity and query-critical dimensions are relational columns.';
